version: 2
updates:
  # Enable version updates for nix
  - package-ecosystem: "nix"
    directory: "/"
    commit-message:
      prefix: build
      include: scope
    allow:
      - dependency-type: "all"
    groups:
      flake-inputs:
        applies-to: "version-updates"
        patterns:
          - "*"
      security:
        applies-to: "security-updates"
        patterns:
          - "*"
    # Configure dependency cooldown to avoid malicious updates
    # This does not affect security updates
    cooldown:
      default-days: 7
      include:
        - "*"
      exclude:
        - "nixpkgs"
    schedule:
      interval: "weekly"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
    directory: "/"
    commit-message:
      prefix: ci
      include: scope
    groups:
      github-actions:
        applies-to: "version-updates"
        patterns:
          - "*"
    # Configure dependency cooldown to avoid malicious updates
    # This does not affect security updates
    cooldown:
      default-days: 7
      include:
        - "*"
    schedule:
      interval: "weekly"
