name: Nix Build

on:
  push:

permissions:
  contents: read
  actions: write

jobs:
  nix-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: nixbuild/nix-quick-install-action@v34
      - id: set-matrix
        name: Generate Nix Matrix
        env:
          NIX_CONFIG: "access-tokens = github.com=${{ github.token }}"
        run: |
          set -Eeu
          matrix="$(nix eval --json '.#githubActions.matrix')"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  nix-build:
    name: ${{ matrix.name }} (${{ matrix.system }})
    needs: nix-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{fromJSON(needs.nix-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: nixbuild/nix-quick-install-action@v34
      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}-
          purge: true
          purge-prefixes: nix-${{ runner.os }}-${{ runner.arch }}-
          purge-created: 0
          purge-primary-key: never
      - name: Build ${{ matrix.attr }}
        env:
          NIX_CONFIG: "access-tokens = github.com=${{ github.token }}"
        run: nix build -L '.#${{ matrix.attr }}'
